# Generated by Django 4.1.2 on 2023-03-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malfunction_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Malfunction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phonebrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('Malfunction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendWebLab.malfunction_type')),
                ('phone_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendWebLab.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Phonetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendWebLab.phonebrand')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendWebLab.phonetype'),
        ),
    ]
